const Lead = require('../models/Lead');
const CRMSettings = require('../models/CRMSettings');
const Timeline = require('../models/Timeline');

/**
 * Format date for Google Ads Offline Conversion Upload
 * Format: yyyy-mm-dd hh:mm:ss+|-hh:mm (e.g. 2026-09-08 10:30:00+05:30)
 */
const formatGoogleAdsDate = (date) => {
  const d = date ? new Date(date) : new Date();
  const pad = (n) => String(n).padStart(2, '0');
  
  const year = d.getFullYear();
  const month = pad(d.getMonth() + 1);
  const day = pad(d.getDate());
  const hours = pad(d.getHours());
  const minutes = pad(d.getMinutes());
  const seconds = pad(d.getSeconds());

  // Determine timezone offset
  const offsetMinutes = -d.getTimezoneOffset();
  const offsetSign = offsetMinutes >= 0 ? '+' : '-';
  const offsetHours = pad(Math.floor(Math.abs(offsetMinutes) / 60));
  const offsetMins = pad(Math.abs(offsetMinutes) % 60);

  return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}${offsetSign}${offsetHours}:${offsetMins}`;
};

/**
 * Get leads with GCLID / GBRAID / WBRAID that have reached converted stage
 */
const getEligibleConversions = async (options = {}) => {
  const {
    stage = 'Admission Confirmed',
    startDate,
    endDate,
    limit = 200
  } = options;

  const query = {
    status: stage,
    $or: [
      { gclid: { $exists: true, $ne: '' } },
      { gbraid: { $exists: true, $ne: '' } },
      { wbraid: { $exists: true, $ne: '' } }
    ]
  };

  if (startDate || endDate) {
    query.updatedAt = {};
    if (startDate) query.updatedAt.$gte = new Date(startDate);
    if (endDate) query.updatedAt.$lte = new Date(endDate);
  }

  const leads = await Lead.find(query)
    .populate('assignedCounsellor', 'name email')
    .sort({ updatedAt: -1 })
    .limit(limit);

  return leads;
};

/**
 * Generate CSV formatted for Google Ads Conversion Import
 * Google Ads Specification:
 * Column 1: Google Click Id
 * Column 2: Conversion Name
 * Column 3: Conversion Time
 * Column 4: Conversion Value
 * Column 5: Conversion Currency
 */
const generateConversionCsv = async (leads, settingsOverride = {}) => {
  let settings = await CRMSettings.findOne();
  if (!settings) settings = await CRMSettings.create({});

  const conversionName = settingsOverride.conversionAction || settings.googleConversionAction || 'School Admission';
  const conversionValue = settingsOverride.conversionValue || settings.googleConversionValue || 5000;
  const currency = settingsOverride.currency || settings.googleConversionCurrency || 'INR';

  // Standard Google Ads Offline Conversion CSV Headers
  const rows = [
    ['Google Click Id', 'Conversion Name', 'Conversion Time', 'Conversion Value', 'Conversion Currency']
  ];

  for (const lead of leads) {
    const clickId = lead.gclid || lead.wbraid || lead.gbraid || '';
    if (!clickId) continue;

    // Find the timeline entry when status became Admission Confirmed
    let conversionTime = lead.updatedAt;
    const admissionEvent = await Timeline.findOne({
      lead: lead._id,
      eventType: 'StatusChange',
      message: { $regex: /Admission Confirmed/i }
    }).sort({ createdAt: -1 });

    if (admissionEvent) {
      conversionTime = admissionEvent.createdAt;
    }

    rows.push([
      clickId,
      conversionName,
      formatGoogleAdsDate(conversionTime),
      conversionValue.toString(),
      currency
    ]);
  }

  // Convert array of arrays to CSV string
  const csvContent = rows
    .map((row) => row.map((field) => `"${String(field).replace(/"/g, '""')}"`).join(','))
    .join('\r\n');

  return {
    csvContent,
    rowCount: rows.length - 1,
    conversionName,
    currency
  };
};

/**
 * Modular API Direct Upload Service (for future Google Ads API Integration)
 *
 * Supports direct upload via Google Ads REST API / Client Library when Developer Token & OAuth are configured.
 */
const uploadConversionsViaApi = async (leads, options = {}) => {
  let settings = await CRMSettings.findOne();
  if (!settings) settings = await CRMSettings.create({});

  const {
    googleCustomerId = settings.googleCustomerId,
    googleDeveloperToken = settings.googleDeveloperToken,
    googleClientId = settings.googleClientId,
    googleRefreshToken = settings.googleRefreshToken
  } = options;

  // Check if API credentials are fully configured
  const hasApiCredentials = Boolean(
    googleCustomerId && googleDeveloperToken && googleClientId && googleRefreshToken
  );

  if (!hasApiCredentials) {
    return {
      success: false,
      status: 'API_CREDENTIALS_REQUIRED',
      message:
        'Direct Google Ads API integration requires Customer ID, Developer Token, and OAuth Refresh Token. Please use the instant CSV Export option to upload to Google Ads UI in the meantime.',
      eligibleConversionsCount: leads.length,
      instructions: [
        '1. Go to Google Ads -> Goals -> Conversions -> Uploads.',
        '2. Download the CSV generated by Cohen CRM.',
        '3. Select source "Upload a file" and click Apply.'
      ]
    };
  }

  // Future Google Ads REST API Call:
  // POST https://googleads.googleapis.com/v17/customers/{customerId}:uploadClickConversions
  // When active, this modular handler dispatches the payload directly to Google's API endpoint.
  return {
    success: true,
    status: 'READY',
    message: `Ready to upload ${leads.length} conversions to Google Ads Account ${googleCustomerId} via API.`,
    uploadedCount: leads.length
  };
};

module.exports = {
  getEligibleConversions,
  generateConversionCsv,
  uploadConversionsViaApi,
  formatGoogleAdsDate
};
